/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-13 23:52:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

public final class patientList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.Map.Entry");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\n");
      out.write("  <title>Patient Data App</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("\n");
      out.write("  ");

    String errorMessage = (String) request.getAttribute("errorMessage");
    if (errorMessage != null) {
  
      out.write("\n");
      out.write("    <div class=\"error-msg\">");
      out.print( errorMessage );
      out.write("</div>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("  ");

    List<String> columnNames    = (List<String>) request.getAttribute("columnNames");
    List<String> selectedColumns = (List<String>) request.getAttribute("selectedColumns");
    List<Map<String, String>> patientData = (List<Map<String, String>>) request.getAttribute("patientData");
  
      out.write("\n");
      out.write("\n");
      out.write("  <div class=\"toolbar\">\n");
      out.write("    <a href=\"editPatient\" class=\"btn btn-success\">+ Add Patient</a>\n");
      out.write("    <a href=\"saveJson\"    class=\"btn btn-secondary\">&#8595; Save as JSON</a>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <form method=\"GET\" action=\"patientList\">\n");
      out.write("    <div class=\"controls\">\n");
      out.write("      <div class=\"search-group\">\n");
      out.write("        <input type=\"text\" name=\"searchstring\" placeholder=\"Search all columns...\"/>\n");
      out.write("        <button type=\"submit\" class=\"btn btn-primary\">Search</button>\n");
      out.write("        <a href=\"patientList\" class=\"btn btn-secondary\">Clear</a>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-selector\">\n");
      out.write("        <strong>Visible Columns</strong>\n");
      out.write("        <div class=\"col-checkboxes\">\n");
      out.write("          ");
 if (columnNames != null) { for (String col : columnNames) { 
      out.write("\n");
      out.write("            <label>\n");
      out.write("              <input type=\"checkbox\" name=\"col\" value=\"");
      out.print( col );
      out.write("\"\n");
      out.write("                ");
      out.print( (selectedColumns != null && selectedColumns.contains(col)) ? "checked" : "" );
      out.write("/>\n");
      out.write("              ");
      out.print( col );
      out.write("\n");
      out.write("            </label>\n");
      out.write("          ");
 } } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <button type=\"submit\" class=\"btn btn-secondary\">Apply</button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </form>\n");
      out.write("\n");
      out.write("  ");

    Map<String, Integer> genderCounts = (Map<String, Integer>) request.getAttribute("genderCounts");
    Map<String, Integer> raceCounts   = (Map<String, Integer>) request.getAttribute("raceCounts");
    if (genderCounts != null) {
      int gTotal = 0; for (int v : genderCounts.values()) gTotal += v;
      int rTotal = 0; for (int v : raceCounts.values())   rTotal += v;
  
      out.write("\n");
      out.write("  <div style=\"margin-top:20px;\">\n");
      out.write("    <table style=\"border:none; width:auto;\">\n");
      out.write("      <tr>\n");
      out.write("        <td style=\"border:none; vertical-align:top; padding-right:40px;\">\n");
      out.write("          <h3>Gender Distribution</h3>\n");
      out.write("          <table class=\"bar-chart\">\n");
      out.write("            ");
 for (Entry<String, Integer> e : genderCounts.entrySet()) {
                 int pct = gTotal > 0 ? e.getValue() * 100 / gTotal : 0; 
      out.write("\n");
      out.write("              <tr>\n");
      out.write("                <td>");
      out.print( e.getKey() );
      out.write("</td>\n");
      out.write("                <td><div class=\"bar\" style=\"width:");
      out.print( pct );
      out.write("%;\"></div></td>\n");
      out.write("                <td>");
      out.print( e.getValue() );
      out.write("</td>\n");
      out.write("              </tr>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("          </table>\n");
      out.write("        </td>\n");
      out.write("        <td style=\"border:none; vertical-align:top;\">\n");
      out.write("          <h3>Race Distribution</h3>\n");
      out.write("          <table class=\"bar-chart\">\n");
      out.write("            ");
 for (Entry<String, Integer> e : raceCounts.entrySet()) {
                 int pct = rTotal > 0 ? e.getValue() * 100 / rTotal : 0; 
      out.write("\n");
      out.write("              <tr>\n");
      out.write("                <td>");
      out.print( e.getKey() );
      out.write("</td>\n");
      out.write("                <td><div class=\"bar\" style=\"width:");
      out.print( pct );
      out.write("%;\"></div></td>\n");
      out.write("                <td>");
      out.print( e.getValue() );
      out.write("</td>\n");
      out.write("              </tr>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("          </table>\n");
      out.write("        </td>\n");
      out.write("      </tr>\n");
      out.write("    </table>\n");
      out.write("  </div>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("  ");

    if (selectedColumns != null && patientData != null) {
      StringBuilder colParams = new StringBuilder();
      for (String col : selectedColumns) colParams.append("&col=").append(col);
  
      out.write("\n");
      out.write("  <div class=\"table-wrapper\">\n");
      out.write("    <table>\n");
      out.write("      <thead>\n");
      out.write("        <tr>\n");
      out.write("          ");
 for (String columnName : selectedColumns) { 
      out.write("\n");
      out.write("            <th>\n");
      out.write("              ");
      out.print( columnName );
      out.write("\n");
      out.write("              <span class=\"sort-links\">\n");
      out.write("                <a href=\"patientList?sort=");
      out.print( columnName );
      out.print( colParams );
      out.write("\">▲</a>\n");
      out.write("                <a href=\"patientList?sortDesc=");
      out.print( columnName );
      out.print( colParams );
      out.write("\">▼</a>\n");
      out.write("              </span>\n");
      out.write("            </th>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("          <th>Actions</th>\n");
      out.write("        </tr>\n");
      out.write("      </thead>\n");
      out.write("      <tbody>\n");
      out.write("        ");
 for (Map<String, String> patient : patientData) { 
      out.write("\n");
      out.write("          <tr>\n");
      out.write("            ");
 for (String columnName : selectedColumns) { 
      out.write("\n");
      out.write("              <td>");
      out.print( patient.get(columnName) != null ? patient.get(columnName) : "" );
      out.write("</td>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            <td>\n");
      out.write("              <div class=\"actions-cell\">\n");
      out.write("                <a href=\"editPatient?index=");
      out.print( patient.get("__idx__") );
      out.write("\" class=\"btn btn-primary\">Edit</a>\n");
      out.write("                <form method=\"POST\" action=\"deletePatient\">\n");
      out.write("                  <input type=\"hidden\" name=\"index\" value=\"");
      out.print( patient.get("__idx__") );
      out.write("\"/>\n");
      out.write("                  <button type=\"submit\" class=\"btn btn-danger\">Delete</button>\n");
      out.write("                </form>\n");
      out.write("              </div>\n");
      out.write("            </td>\n");
      out.write("          </tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </tbody>\n");
      out.write("    </table>\n");
      out.write("  </div>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
